#!/usr/bin/env node
/**
 * Scans data/work.js for projects with no thumbnail and for inline
 * <!-- IMAGES: ... --> notes, then writes IMAGES.md.
 *
 * Run with: npm run images
 *
 * Re-run it after adding artwork — entries drop off the list automatically
 * once their thumbnail field is filled in.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');

function load(file, globalName) {
  const src = fs.readFileSync(path.join(ROOT, file), 'utf8');
  const tmp = path.join(require('os').tmpdir(), `_${globalName}_${Date.now()}.js`);
  fs.writeFileSync(tmp, `${src}\nmodule.exports = ${globalName};`);
  const value = require(tmp);
  fs.unlinkSync(tmp);
  return value;
}

const PROJECTS = load('data/work.js', 'PROJECTS');

const DISCIPLINE_ORDER = ['screen', 'stage', 'print', 'music', 'worldbuilding', 'tech', 'visual'];

/* Which folder an entry's images belong in. Existing entries already follow
   assets/images/<id>/, so suggest the same for the ones that are missing. */
const folderFor = (p) => `assets/images/${p.id}/`;

const missingThumb = PROJECTS.filter((p) => !p.thumbnail || !p.thumbnail.trim());
const haveThumb = PROJECTS.filter((p) => p.thumbnail && p.thumbnail.trim());

/* Inline notes left in the content HTML */
const inlineNotes = [];
PROJECTS.forEach((p) => {
  const re = /<!--\s*IMAGES:\s*([\s\S]*?)-->/g;
  let m;
  while ((m = re.exec(p.content || '')) !== null) {
    inlineNotes.push({ project: p, note: m[1].replace(/\s+/g, ' ').trim() });
  }
});

/* Referenced image files that don't exist on disk */
const broken = [];
PROJECTS.forEach((p) => {
  const refs = [];
  if (p.thumbnail && p.thumbnail.trim()) refs.push(p.thumbnail.trim());
  const re = /<img[^>]+src="([^"]+)"/g;
  let m;
  while ((m = re.exec(p.content || '')) !== null) refs.push(m[1]);

  refs.forEach((ref) => {
    if (/^https?:/.test(ref)) return;
    const rel = ref.replace(/^\.\.\//, '').replace(/^\.\//, '');
    if (!fs.existsSync(path.join(ROOT, rel))) broken.push({ project: p, ref });
  });
});

/* ---- Report ---- */

const L = [];
L.push('# Images still needed');
L.push('');
L.push('> Generated by `npm run images` — re-run it after adding artwork.');
L.push(`> ${haveThumb.length} of ${PROJECTS.length} projects have a thumbnail.`);
L.push('');
L.push('Thumbnails are the cover image on `projects.html` and the homepage cards.');
L.push('Without one, a project renders a grey "No image" placeholder.');
L.push('');
L.push('To add one: drop the file in the folder below, then set `thumbnail` on that');
L.push("entry in `data/work.js` (path is relative to the site root, no leading `/`).");
L.push('');

L.push('## 1. Missing thumbnails');
L.push('');
if (!missingThumb.length) {
  L.push('None — every project has a thumbnail.');
} else {
  L.push('| Project | Discipline | Put the file here | Then set in `data/work.js` |');
  L.push('|---|---|---|---|');
  missingThumb
    .slice()
    .sort((a, b) => DISCIPLINE_ORDER.indexOf(a.discipline) - DISCIPLINE_ORDER.indexOf(b.discipline))
    .forEach((p) => {
      L.push(
        `| **${p.title}** | ${p.discipline} | \`${folderFor(p)}\` | \`thumbnail: '${folderFor(p)}thumbnail.jpg'\` |`
      );
    });
}
L.push('');

L.push('## 2. Suggested in-page images');
L.push('');
L.push('Places inside a project body where an image would help. These are marked');
L.push('with an `<!-- IMAGES: ... -->` comment in `data/work.js` — search for');
L.push('`IMAGES:` to find the exact spot, then replace the comment with an');
L.push('`<img>` or an `.image-grid` block (see **Into A Dream** for the pattern).');
L.push('');
if (!inlineNotes.length) {
  L.push('None outstanding.');
} else {
  inlineNotes.forEach(({ project, note }) => {
    L.push(`- **${project.title}** (\`#${project.id}\`) — ${note}`);
  });
}
L.push('');

L.push('## 3. Broken image references');
L.push('');
if (!broken.length) {
  L.push('None — every referenced image exists on disk.');
} else {
  L.push('These paths are referenced but the file is missing:');
  L.push('');
  broken.forEach(({ project, ref }) => {
    L.push(`- **${project.title}** → \`${ref}\``);
  });
}
L.push('');

fs.writeFileSync(path.join(ROOT, 'IMAGES.md'), L.join('\n'));

console.log(`IMAGES.md written.`);
console.log(`  missing thumbnails : ${missingThumb.length}`);
console.log(`  in-page suggestions: ${inlineNotes.length}`);
console.log(`  broken references  : ${broken.length}`);
